__title__ = 'zkafka'
__description__ = 'Ziro Kafka'
__url__ = 'https://github.com/rideziro/zkafka'
__version__ = '1.5.0'
__build__ = 0x150
__author__ = 'Alfred Jayag'
__author_email__ = 'alfred@newsinbullets.app'
__license__ = 'MIT License'
__copyright__ = 'Copyright 2020 Alfred Jayag'